version: "3.8"

services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: todoDB
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    container_name: backend
    restart: always
    environment:
      PORT: 5000
      MONGODB_URI: "mongodb://mongodb:27017/todoDB"
      NEW_RELIC_LICENSE_KEY: "YOUR_NEW_RELIC_LICENSE_KEY"
      NEW_RELIC_APP_NAME: "MERN Observability Demo"
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo-data:
